In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_1.csv',encoding='cp949')
df1.dropna(inplace=True)
df1.reset_index(drop=True,inplace=True)

df1

             회사명  거래소코드     회계년도 통계청 한국표준산업분류 10차(대분류)
0          (주)3Z  12815  2018/12                   제조업
1       (주)88스테이  81962  2018/12                  부동산업
2       (주)A.M.C  64118  2018/12                   제조업
3     (주)DCFTREK  17676  2018/12                   제조업
4       (주)DH케미칼  40581  2018/12                   제조업
...          ...    ...      ...                   ...
3719   동덕산업가스(주)  46182  2018/12                   제조업
3720   동덕정보통신(주)  73877  2018/12              도매 및 소매업
3721     동도건설(주)  14039  2018/12                   건설업
3722    동도디앤씨(주)  42171  2018/12                   건설업
3723   동도씨앤디주식회사  69794  2018/12                  부동산업

[3724 rows x 4 columns]

In [3]:
df2 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_2.csv',encoding='cp949')
df2.dropna(inplace=True)
df2.reset_index(drop=True,inplace=True)

df2

              회사명  거래소코드     회계년도    통계청 한국표준산업분류 10차(대분류)
0         (주)동도전자  14041  2018/12                      제조업
1     (주)동래온천관광호텔  87237  2018/12                숙박 및 음식점업
2        (주)동림모스텍  80815  2018/12                 운수 및 창고업
3         (주)동림수산  46127  2018/12                      제조업
4         (주)동림유화  41229  2018/12                      제조업
...           ...    ...      ...                      ...
3601   삼지석재공업주식회사  15178  2018/12                      제조업
3602   삼지정밀기계주식회사  63574  2018/12                      제조업
3603      삼지토건(주)  43997  2018/12                      건설업
3604     삼진기업주식회사  24180  2018/12  수도, 하수 및 폐기물 처리, 원료 재생업
3605      삼진로푸(주)  65154  2018/12                      제조업

[3606 rows x 4 columns]

In [4]:
df3 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_3.csv',encoding='cp949')
df3.dropna(inplace=True)
df3.reset_index(drop=True,inplace=True)

df3

                 회사명  거래소코드     회계년도  통계청 한국표준산업분류 10차(대분류)
0           (유)새천안교통  89201  2018/12               운수 및 창고업
1          (주)삼진앤컴퍼니  15181  2018/12                   부동산업
2           (주)삼진일렉스  52542  2018/12                    건설업
3            (주)삼진전선  41282  2018/12                    제조업
4            (주)삼진정밀  38845  2018/12                    제조업
...              ...    ...      ...                    ...
3621     에스앤에스엠텍주식회사  72842  2018/12                    제조업
3622    에스앤에스이앤지주식회사  59774  2018/12                    제조업
3623     에스앤에스케어텍(주)  80268  2018/12               도매 및 소매업
3624      에스앤이에너지(주)  76349  2018/12  전기, 가스, 증기 및 공기조절 공급업
3625  에스앤제이이노베이션주식회사  71004  2018/12               도매 및 소매업

[3626 rows x 4 columns]

In [5]:
df4 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_4.csv',encoding='cp949')
df4.dropna(inplace=True)
df4.reset_index(drop=True,inplace=True)

df4

               회사명  거래소코드     회계년도 통계청 한국표준산업분류 10차(대분류)
0        (유)유맥에프앤알  14534  2018/12                  부동산업
1          (주)에스앤지  60521  2018/12                   제조업
2      (주)에스앤지바이오텍  82030  2018/12                   제조업
3       (주)에스앤지컴퍼니  56486  2018/12                   제조업
4     (주)에스앤지홀딩스서울  89402  2018/12                  부동산업
...            ...    ...      ...                   ...
3571      인성제약주식회사  89564  2018/12                   제조업
3572      인성피앤씨(주)  61151  2018/12                   제조업
3573        인셀주식회사  77133  2018/12                   제조업
3574        인솔주식회사  88739  2018/12                   제조업
3575      인수약품주식회사  69195  2018/12              도매 및 소매업

[3576 rows x 4 columns]

In [6]:
df5 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_5.csv',encoding='cp949')
df5.dropna(inplace=True)
df5.reset_index(drop=True,inplace=True)

df5

               회사명  거래소코드     회계년도     통계청 한국표준산업분류 10차(대분류)
0           (주)인스빌  39379  2018/12                      부동산업
1        (주)인스타디앤씨  87283  2018/12                      부동산업
2           (주)인스텍  85404  2018/12                       제조업
3            (주)인아  82697  2018/12                       제조업
4      (주)인아오리엔탈모터  25922  2018/12                       제조업
...            ...    ...      ...                       ...
3751  주식회사삼육리더스라이프  81833  2018/12  협회 및 단체, 수리 및 기타 개인 서비스업
3752     주식회사삼융시네마  91582  2018/12                      부동산업
3753    주식회사삼익유니버스  69725  2018/12                      부동산업
3754    주식회사삼익티디에프  52316  2018/12                       제조업
3755      주식회사삼인건설  82195  2018/12                       건설업

[3756 rows x 4 columns]

In [7]:
df6 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_6.csv',encoding='cp949')
df6.dropna(inplace=True)
df6.reset_index(drop=True,inplace=True)

df6

                회사명  거래소코드     회계년도 통계청 한국표준산업분류 10차(대분류)
0          주식회사삼일산업  81417  2018/12              도매 및 소매업
1        주식회사삼일에쓰아이  71265  2018/12                  부동산업
2         주식회사삼일이엔씨  81434  2018/12                  부동산업
3         주식회사삼일이엔씨  71111  2018/12                  부동산업
4          주식회사삼일통상  52616  2018/12              도매 및 소매업
...             ...    ...      ...                   ...
3785  주식회사최고좋은터행복한집  81447  2018/12                  부동산업
3786   주식회사최신EPPEPS  59563  2018/12                   제조업
3787       주식회사충남고속  26812  2018/12              운수 및 창고업
3788       주식회사충주산업  84889  2018/12                   제조업
3789         주식회사친구  87052  2018/12                  부동산업

[3790 rows x 4 columns]

In [8]:
df7 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_7.csv',encoding='cp949')
df7.dropna(inplace=True)
df7.reset_index(drop=True,inplace=True)

df7

             회사명  거래소코드     회계년도    통계청 한국표준산업분류 10차(대분류)
0          (주)주안  78796  2018/12                     부동산업
1          (주)주안  84937  2018/12                      제조업
2          (주)주영  85463  2018/12                      제조업
3        (주)주영토건  89235  2018/12                      건설업
4      (주)주영페이퍼텍  70977  2018/12                      제조업
...          ...    ...      ...                      ...
3652  태산종합건설주식회사  26928  2018/12                      건설업
3653    태산테크주식회사  66114  2018/12                      제조업
3654  태산하이테크주식회사  87236  2018/12                      제조업
3655  태서리사이클링(주)  19376  2018/12  수도, 하수 및 폐기물 처리, 원료 재생업
3656   태성글로벌주식회사  90489  2018/12                 도매 및 소매업

[3657 rows x 4 columns]

In [9]:
df8 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업업종 종합/기업명12_18_8.csv',encoding='cp949')
df8.dropna(inplace=True)
df8.reset_index(drop=True,inplace=True)

df8

            회사명  거래소코드     회계년도 통계청 한국표준산업분류 10차(대분류)
0       (주)태성기연  43667  2018/12                   제조업
1       (주)태성기전  82372  2018/12                   제조업
2      (주)태성비앤피  53635  2018/12                  부동산업
3       (주)태성비철  57262  2018/12              도매 및 소매업
4     (주)태성에스앤디  83308  2018/12                   건설업
...         ...    ...      ...                   ...
3296       힐리언스  49187  2018/12             숙박 및 음식점업
3297   힐링홈스주식회사  84799  2018/12                   건설업
3298   힐중공업주식회사  82007  2018/12                   제조업
3299  힐티코리아주식회사  10534  2018/12              도매 및 소매업
3300  （주）신미코스메틱  85105  2018/12              도매 및 소매업

[3301 rows x 4 columns]

In [10]:
import numpy as np

df_w = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8],axis=0)
df_w.reset_index(inplace=True,drop=True)
df_w.rename(columns={'회사명':'구분'},inplace=True)
df_w.rename(columns={'통계청 한국표준산업분류 10차(대분류)':'업종'},inplace=True)
df_w.set_index('구분',inplace=True)
df_w = df_w['업종']
df_w

구분
(주)3Z               제조업
(주)88스테이           부동산업
(주)A.M.C            제조업
(주)DCFTREK          제조업
(주)DH케미칼            제조업
                ...
힐리언스          숙박 및 음식점업
힐링홈스주식회사            건설업
힐중공업주식회사            제조업
힐티코리아주식회사      도매 및 소매업
（주）신미코스메틱      도매 및 소매업
Name: 업종, Length: 29036, dtype: object

In [11]:
df13 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/13_15_이자.csv',encoding='cp949')
df13.set_index('구분',inplace=True)
df13 = df13.join(df_w,how='left')
# df13.index[df13['업종']=='금융 및 보험업']
df13['업종'][df13['업종'] != '제조업'] = 1
df13['업종'][df13['업종'] == '제조업'] = 0
ind = df13['업종']
df13.drop('업종',axis=1,inplace=True)
df13.insert(loc=31,column='업종',value=ind)
df13
# 비제조업 1, 제조업 0
# df13.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/13_15_이자(업종더미).csv',encoding='cp949')
# 업종 추가 결과 데이터 숫자가 더 늘어나게 되는데
# 특정 기업이 여러 업종에서 사업을 진행할 경우 
# 해당 업종별로 개별 데이터로 취급하기 때문이다.

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1438019559.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13['업종'][df13['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1438019559.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13['업종'][df13['업종'] == '제조업'] = 0

,총자산증가율2015,유동자산증가율2015,매출액증가율2015,매출액순이익률2015,매출총이익률2015,자기자본순이익률2015,총자산순이익률2015,매출원가대매출액비율2015,매출액대판매관리비2015,매출채권회전율2015,...,부채/현금흐름2015,유동부채/부채2015,총부채/총자산2015,유동부채/총부채2015,유동자산/총자산2015,현금흐름/매출액2015,이자보상배율2015,차입금평균금리2015,업종,정상기업여부
구분,,,,,,,,,,,,,,,,,,,,,
(주)DCFTREK,-0.206510,-0.411713,-0.051827,-0.057325,0.052088,-0.099225,-0.074681,0.947912,0.033682,22.019158,...,-6.745398,1.280079,0.247360,0.788517,0.155350,-0.017339,3.290545,3.26,0,1
(주)EG메탈,-0.193725,-0.357382,-0.163192,-0.161087,-0.093977,-0.375193,-0.212130,1.093977,0.039236,12.905227,...,-20.201354,0.159699,0.434611,0.141441,0.368828,-0.014469,-11.924295,3.82,1,0
(주)JBM,-0.145278,-0.141874,-0.030179,-0.159231,0.063887,-2.242065,-0.165890,0.936113,0.134091,16.114076,...,-38.398532,1.167988,0.926010,0.584150,0.385122,-0.011577,-3.070547,4.55,0,0
(주)가현산업개발,-0.046064,-0.265191,0.174658,-0.499012,0.993855,-0.062430,-0.016031,0.006145,0.713376,21.099711,...,3920.645161,1.006669,0.743213,0.936759,0.108809,0.005491,0.287763,4.53,1,0
(주)갑우문화사,0.007544,-0.045211,0.013393,0.016243,0.145534,0.021229,0.014784,0.854466,0.130975,6.093672,...,6.158151,1.993471,0.303589,0.612345,0.245989,0.016638,4.482982,3.08,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
휘닉스중앙제주주식회사,-0.050876,0.652269,0.089258,-0.243080,0.881424,-0.508726,-0.034584,0.118576,0.615095,36.327392,...,1761.208708,0.699572,0.932018,0.138192,0.019802,0.000735,1.091155,19.53,1,1
휘닉스중앙주식회사,-0.057541,-0.182054,-0.062828,-0.664646,1.000000,-1.255633,-0.071971,0.000000,1.129791,14.172147,...,-16.520532,1.823555,0.942681,0.471166,0.077815,-0.136153,-0.528428,10.50,1,0
휴먼전자주식회사,-0.041699,-0.038679,0.108428,-0.018043,0.042102,-0.029274,-0.020194,0.957898,0.055636,4.785195,...,-29.325206,0.329634,0.310172,0.267124,0.393914,-0.007658,-2.717544,2.11,0,0
흥일기업주식회사,0.116936,0.487886,0.012267,0.004847,0.163233,0.012013,0.002961,0.836767,0.098896,13.621891,...,111.092079,0.777396,0.753492,0.509321,0.346773,0.007273,1.765804,4.75,0,1
흥진기업(주),0.113080,-0.002043,0.081999,0.026628,0.075770,0.029262,0.021301,0.924230,0.096101,5.777642,...,9.999331,1.536704,0.272073,0.676539,0.255712,0.014975,-9.871061,2.17,0,0

In [16]:
df13 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/13_15_영손.csv',encoding='cp949')
df13.set_index('구분',inplace=True)
df13 = df13.join(df_w,how='left')
# df13.index[df13['업종']=='금융 및 보험업']
df13['업종'][df13['업종'] != '제조업'] = 1
df13['업종'][df13['업종'] == '제조업'] = 0
ind = df13['업종']
df13.drop('업종',axis=1,inplace=True)
df13.insert(loc=31,column='업종',value=ind)
df13
# 비제조업 1, 제조업 0
df13.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/13_15_영손(업종더미).csv',encoding='cp949')
# 업종 추가 결과 데이터 숫자가 더 늘어나게 되는데
# 특정 기업이 여러 업종에서 사업을 진행할 경우 
# 해당 업종별로 개별 데이터로 취급하기 때문이다.

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1546081181.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13['업종'][df13['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1546081181.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13['업종'][df13['업종'] == '제조업'] = 0

In [18]:
df14 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/14_16_이자.csv',encoding='cp949')
df14.set_index('구분',inplace=True)
df14 = df14.join(df_w,how='left')
df14['업종'][df14['업종'] != '제조업'] = 1
df14['업종'][df14['업종'] == '제조업'] = 0
ind = df14['업종']
df14.drop('업종',axis=1,inplace=True)
df14.insert(loc=31,column='업종',value=ind)
df14
# 비제조업 1, 제조업 0
# df14.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/14_16이자(업종더미).csv',encoding='cp949')
# df14.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/14_16_이자(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\298851460.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df14['업종'][df14['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\298851460.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df14['업종'][df14['업종'] == '제조업'] = 0

,총자산증가율2016,유동자산증가율2016,매출액증가율2016,매출액순이익률2016,매출총이익률2016,자기자본순이익률2016,총자산순이익률2016,매출원가대매출액비율2016,매출액대판매관리비2016,매출채권회전율2016,...,부채/현금흐름2016,유동부채/부채2016,총부채/총자산2016,유동부채/총부채2016,유동자산/총자산2016,현금흐름/매출액2016,이자보상배율2016,차입금평균금리2016,업종,정상기업여부
구분,,,,,,,,,,,,,,,,,,,,,
(주)A.M.C,-0.096093,-0.225289,-0.027823,-0.189179,0.062002,-0.315763,-0.107240,0.937998,0.190877,4.061668,...,-553.476272,0.522244,0.660378,0.414574,0.233414,-0.001671,-4.044189,3.29,0,0
(주)EG메탈,0.022418,0.188799,-0.398421,-0.066588,0.003415,-0.102901,-0.051595,0.996585,0.057418,10.243580,...,4.686861,0.314880,0.498602,0.258793,0.428848,0.112843,-3.181603,3.35,1,0
(주)JBM,-0.054860,-0.166440,0.029369,0.005861,0.111307,0.060056,0.006651,0.888693,0.089013,15.610926,...,-112.606623,0.922616,0.889261,0.464005,0.339656,-0.003500,1.160782,4.32,0,1
(주)KH엘텍,0.233715,1.364335,0.123236,-0.053717,0.027891,-0.711161,-0.082287,0.972109,0.077201,7.543891,...,12.423751,2.056262,0.884291,0.931575,0.376363,0.021050,-5.428667,3.49,0,0
(주)S-Tech,0.111936,1.550841,7.877261,0.121937,0.599890,0.063715,0.058211,0.400110,0.586608,8.004863,...,0.000849,1110.705000,0.086393,0.750534,0.198379,0.144007,6787.875000,3.20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
화인산업(주),0.134861,-0.418742,-0.528399,0.555645,0.562456,0.062618,0.032342,0.437544,1.102788,12.560140,...,-39.965882,0.988930,0.483495,0.704629,0.024772,-0.148089,-3.854016,2.95,0,0
후지라이테크(주),-0.066820,0.004685,-0.055189,-0.034096,0.310388,-0.054007,-0.022774,0.689612,0.273473,8.320096,...,8.358736,1.077636,0.578323,0.554107,0.421065,0.053262,1.842945,2.73,0,1
휘닉스중앙주식회사,0.113948,1.184975,0.016147,-0.162379,1.000000,-0.039435,-0.016039,0.000000,1.136513,8.934258,...,0.072810,63.943658,0.593271,0.648352,0.152632,0.836400,-0.648358,15.06,1,0
휴먼전자주식회사,0.051479,0.014160,-0.222966,0.082350,0.080245,0.095098,0.068111,0.919755,0.057861,7.960166,...,-9.364548,0.294217,0.283782,0.234224,0.379933,-0.029168,3.103114,2.57,0,1
흥진기업(주),0.064721,-0.129223,0.099478,0.004348,0.041208,0.005389,0.003592,0.958792,0.098610,5.657491,...,-91.394300,1.046133,0.333490,0.540874,0.209133,-0.002284,-11.430306,2.91,0,0

In [19]:
df14 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/14_16_영손.csv',encoding='cp949')
df14.set_index('구분',inplace=True)
df14 = df14.join(df_w,how='left')
df14['업종'][df14['업종'] != '제조업'] = 1
df14['업종'][df14['업종'] == '제조업'] = 0
ind = df14['업종']
df14.drop('업종',axis=1,inplace=True)
df14.insert(loc=31,column='업종',value=ind)
df14
# 비제조업 1, 제조업 0
df14.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/14_16영손(업종더미).csv',encoding='cp949')
# df14.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/14_16_영손(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3843066413.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df14['업종'][df14['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3843066413.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df14['업종'][df14['업종'] == '제조업'] = 0

In [13]:
df15 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/15_17_이자.csv',encoding='cp949')
df15.set_index('구분',inplace=True)
df15 = df15.join(df_w,how='left')
df15['업종'][df15['업종'] != '제조업'] = 1
df15['업종'][df15['업종'] == '제조업'] = 0
ind = df15['업종']
df15.drop('업종',axis=1,inplace=True)
df15.insert(loc=31,column='업종',value=ind)
df15
# 비제조업 1, 제조업 0
# df15.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/15_17이자(업종더미).csv',encoding='cp949')
# df15.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/15_17_이자(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3442791194.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df15['업종'][df15['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3442791194.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df15['업종'][df15['업종'] == '제조업'] = 0

In [20]:
df15 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/15_17_영손.csv',encoding='cp949')
df15.set_index('구분',inplace=True)
df15 = df15.join(df_w,how='left')
df15['업종'][df15['업종'] != '제조업'] = 1
df15['업종'][df15['업종'] == '제조업'] = 0
ind = df15['업종']
df15.drop('업종',axis=1,inplace=True)
df15.insert(loc=31,column='업종',value=ind)
df15
# 비제조업 1, 제조업 0
df15.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/15_17영손(업종더미).csv',encoding='cp949')
# df15.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/15_17_영손(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1741742824.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df15['업종'][df15['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\1741742824.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df15['업종'][df15['업종'] == '제조업'] = 0

In [14]:
df16 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/16_18_이자.csv',encoding='cp949')
df16.set_index('구분',inplace=True)
df16 = df16.join(df_w,how='left')
df16['업종'][df16['업종'] != '제조업'] = 1
df16['업종'][df16['업종'] == '제조업'] = 0
ind = df16['업종']
df16.drop('업종',axis=1,inplace=True)
df16.insert(loc=31,column='업종',value=ind)
df16
# 비제조업 1, 제조업 0
# df16.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/16_18이자(업종더미).csv',encoding='cp949')
# df16.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/16_18_이자(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3944288534.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df16['업종'][df16['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\3944288534.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df16['업종'][df16['업종'] == '제조업'] = 0

In [22]:
df16 = pd.read_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/땡처리 삭제/정상기간/16_18_영손.csv',encoding='cp949')
df16.set_index('구분',inplace=True)
df16 = df16.join(df_w,how='left')
df16['업종'][df16['업종'] != '제조업'] = 1
df16['업종'][df16['업종'] == '제조업'] = 0
ind = df16['업종']
df16.drop('업종',axis=1,inplace=True)
df16.insert(loc=31,column='업종',value=ind)
df16
# 비제조업 1, 제조업 0
df16.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/더미화/정상기간/16_18영손(업종더미).csv',encoding='cp949')
# df16.to_csv('C:/Users/LG/Desktop/금융 빅데이터/프로젝트2/코드/재무비율 계산 버전/cross_check/기업재무비율_업종포함/정상기간/16_18_영손(업종포함).csv',encoding='cp949')

C:\Users\LG\AppData\Local\Temp\ipykernel_8584\4244497209.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df16['업종'][df16['업종'] != '제조업'] = 1
C:\Users\LG\AppData\Local\Temp\ipykernel_8584\4244497209.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df16['업종'][df16['업종'] == '제조업'] = 0